# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76ae8d2b902bd7d3e001af48926233360dac662a7fc4b1e696e261e0f61e9105cb420fd582d32847804e944da4b5379c5ee1d1758b1acf3f5ef76e4a8cde95bb

test:
  secret_key_base: e189749e931dc3ab57f18e324175dbb6330019846428dba23959b7635540468dfd326c2e42e47c4f0044e9906d326c1c40d2f6de0630664687a3f1b0efa244f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
